var labelList = [
{id:	0	,name:'法人代表变更 '},	
{id:	1	,name:'频繁变更法人代表'},	
{id:	2	,name:'股东变更'},								
{id:	3	,name:'频繁变更股东'},			
{id:	4	,name:'高管变更'},								
{id:	5	,name:'频繁变更高管'},
{id:	6	,name:'经营异常'},								
{id:	7	,name:'企业更名'},								
{id:	8	,name:'企业吊销注销'},			
{id:	9	,name:'对外扩张'},								
{id:	10	,name:'新增对外投资'},							
{id:	11	,name:'新增对外融资'},								
{id:	12	,name:'资产冻结'},								
{id:	13	,name:'行政处罚'},								
{id:	14	,name:'欠税'},								
{id:	15	,name:'税务信息非正常'},								
{id:	16	,name:'涉诉'},								
{id:	17	,name:'舆情动态'},								
{id:	18	,name:'重点关注舆情'},								
{id:	19	,name:'新增专利'},								
{id:	20	,name:'新增招投标'},								
{id:	21	,name:'新增商标'},								
{id:	22	,name:'疑似个人涉诉'},								
{id:	23	,name:'个人涉诉'}						
];